// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/playlist/playlist.proto

package music

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePlayListRq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tracks               []*Track `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayListRq) Reset()         { *m = CreatePlayListRq{} }
func (m *CreatePlayListRq) String() string { return proto.CompactTextString(m) }
func (*CreatePlayListRq) ProtoMessage()    {}
func (*CreatePlayListRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25b741c62f292238, []int{0}
}

func (m *CreatePlayListRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayListRq.Unmarshal(m, b)
}
func (m *CreatePlayListRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayListRq.Marshal(b, m, deterministic)
}
func (m *CreatePlayListRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayListRq.Merge(m, src)
}
func (m *CreatePlayListRq) XXX_Size() int {
	return xxx_messageInfo_CreatePlayListRq.Size(m)
}
func (m *CreatePlayListRq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayListRq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayListRq proto.InternalMessageInfo

func (m *CreatePlayListRq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePlayListRq) GetTracks() []*Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type CreatePlayListRs struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayListRs) Reset()         { *m = CreatePlayListRs{} }
func (m *CreatePlayListRs) String() string { return proto.CompactTextString(m) }
func (*CreatePlayListRs) ProtoMessage()    {}
func (*CreatePlayListRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_25b741c62f292238, []int{1}
}

func (m *CreatePlayListRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayListRs.Unmarshal(m, b)
}
func (m *CreatePlayListRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayListRs.Marshal(b, m, deterministic)
}
func (m *CreatePlayListRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayListRs.Merge(m, src)
}
func (m *CreatePlayListRs) XXX_Size() int {
	return xxx_messageInfo_CreatePlayListRs.Size(m)
}
func (m *CreatePlayListRs) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayListRs.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayListRs proto.InternalMessageInfo

func (m *CreatePlayListRs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePlayListRs) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Track struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_25b741c62f292238, []int{2}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePlayListRq)(nil), "music.CreatePlayListRq")
	proto.RegisterType((*CreatePlayListRs)(nil), "music.CreatePlayListRs")
	proto.RegisterType((*Track)(nil), "music.Track")
}

func init() { proto.RegisterFile("proto/playlist/playlist.proto", fileDescriptor_25b741c62f292238) }

var fileDescriptor_25b741c62f292238 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xc8, 0x49, 0xac, 0xcc, 0xc9, 0x2c, 0x2e, 0x81, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0xac, 0xb9, 0xa5, 0xc5, 0x99, 0xc9, 0x4a, 0x3e, 0x5c, 0x02, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9,
	0x01, 0x39, 0x89, 0x95, 0x3e, 0x99, 0xc5, 0x25, 0x41, 0x85, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89,
	0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x0a, 0x17, 0x5b, 0x49,
	0x51, 0x62, 0x72, 0x76, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x8f, 0x1e, 0x58, 0xbf,
	0x5e, 0x08, 0x48, 0x30, 0x08, 0x2a, 0xa7, 0x64, 0x85, 0x61, 0x5a, 0x31, 0x56, 0xd3, 0x84, 0xb8,
	0x58, 0x8a, 0x33, 0xab, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x25, 0x69,
	0x2e, 0x56, 0xb0, 0x61, 0xd8, 0x34, 0x18, 0x85, 0x73, 0xf1, 0xc3, 0x8c, 0x0c, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x15, 0x72, 0xe1, 0xe2, 0x4b, 0x46, 0xb1, 0x4b, 0x48, 0x1c, 0xea, 0x26, 0x74,
	0x0f, 0x49, 0xe1, 0x90, 0x28, 0x56, 0x62, 0x48, 0x62, 0x03, 0x87, 0x86, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0xdb, 0xab, 0x3b, 0x2e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayListServiceClient is the client API for PlayListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayListServiceClient interface {
	CreatePlayList(ctx context.Context, in *CreatePlayListRq, opts ...grpc.CallOption) (*CreatePlayListRs, error)
}

type playListServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayListServiceClient(cc *grpc.ClientConn) PlayListServiceClient {
	return &playListServiceClient{cc}
}

func (c *playListServiceClient) CreatePlayList(ctx context.Context, in *CreatePlayListRq, opts ...grpc.CallOption) (*CreatePlayListRs, error) {
	out := new(CreatePlayListRs)
	err := c.cc.Invoke(ctx, "/music.PlayListService/createPlayList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayListServiceServer is the server API for PlayListService service.
type PlayListServiceServer interface {
	CreatePlayList(context.Context, *CreatePlayListRq) (*CreatePlayListRs, error)
}

// UnimplementedPlayListServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayListServiceServer struct {
}

func (*UnimplementedPlayListServiceServer) CreatePlayList(ctx context.Context, req *CreatePlayListRq) (*CreatePlayListRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayList not implemented")
}

func RegisterPlayListServiceServer(s *grpc.Server, srv PlayListServiceServer) {
	s.RegisterService(&_PlayListService_serviceDesc, srv)
}

func _PlayListService_CreatePlayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayListRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayListServiceServer).CreatePlayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/music.PlayListService/CreatePlayList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayListServiceServer).CreatePlayList(ctx, req.(*CreatePlayListRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayListService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "music.PlayListService",
	HandlerType: (*PlayListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createPlayList",
			Handler:    _PlayListService_CreatePlayList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/playlist/playlist.proto",
}
